### ISSUE TITLE
DEA Sandbox - dc.load for Collection 2 wofs errors if crs and resolution are not specified

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-config#405]
Error - dc.load has an error about crs and resolution.
Dave: Product definition for Collection 2 `wofs_albers` has issues. Need to specify output_crs and resolution now, and did not need to in the past. Fix: log the bug with dea-config, it's a bug with the AWS product definitions.  @GypsyBojangles

**Comment by Kirill888** [comment]
done with #406, sandbox db was updated with new product spec doc
