### ISSUE TITLE
Spectral reflectance curves not working

### ISSUE THREAD

**Issue by LeoLym** [GeoscienceAustralia/dea-config#558]
The spectral reflecance curves are no longer working.  The values come back in a table, but the plotted curve throws a NaN
![image](https://user-images.githubusercontent.com/37321366/87369391-bee20700-c5c3-11ea-82c8-45da1f92e600.png)
http://terria-cube.terria.io/#share=s-kMQexFTrHUncRQZdN2HLjK0rsip

**Comment by LeoLym** [comment]
The plot capability is working now.  Yay!  But when you click expand, it jumps and dumps the new one down, rather than adding to the existing selection (earlier versions allowed you to click on multiple points, and expand the spectra so that you could compare multiple spectra

https://maps.dea.ga.gov.au/#share=s-rMdJ9KJ1y6RVEbt6BH7pjePlsNG

**Comment by robbibt** [comment]
A related issue here is the mismatch between the feature info table rows and the styles that are available for the layer. For example, [you can visualise the MNDWI and NDCI indices for Sentinel-2 products](http://terria-cube.terria.io/#share=s-yZU6TgfhwgW6ChbSAb1CygUdlja), but you can't click on the map and get a value back (currently, only the NDWI and NDVI indices are available in the feature info):

![image](https://user-images.githubusercontent.com/17680388/108290435-81da9480-71e4-11eb-98a3-8bb9086c2b9d.png)

This could be resolved by adding all spectral bands and indices available in a layer's Styles drop down to the feature info table.

**Comment by GypsyBojangles** [comment]
Fixed with PR #669
