### ISSUE TITLE
OWS layer request - [TASSELED CAP]

### ISSUE THREAD

**Issue by vnewey** [GeoscienceAustralia/dea-config#618]
## Input for ows ##

|  ows config fieldname |  request                             |
| -------------------------| -----------------------------|
| Title:                |  DEA Wetness Percentiles (Landsat) |
| Product name: | ga_ls_tcw_percentiles_2  |
| ows layer name:  | ga_ls_tcw_percentiles_2  |
| data description: |  Geoscience Australia Landsat Collection 2 Tasselled Cap Wetness Percentiles 1986-2018, 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577). Data is only visible at higher resolutions; when zoomed-out the available area will be displayed as a shaded region. 

Areas that are partially covered in water, or where water is mixed with vegetation when viewed from above provide habitat for a wide range of aquatic organisms. 

The ability to map partial inundation is also crucial to understand patterns of human water use. We need to be able to identify potential wetlands and groundwater dependent ecosystems on the Australian continent so that they can be monitored and managed. 

The tasseled cap wetness percentiles provide a multi-decadal summary of landscape wetness that can be used to identify wetlands and groundwater ecosystems.

They provide statistical summaries (10th, 50th and 90th percentiles) of the tasseled cap wetness index from 1987 to 2017.

They are intended for use as inputs into classification algorithms to identify potential wetlands and groundwater dependent ecosystems, and characterise salt flats, clay pans, salt lakes and coastal land forms.

This product provides valuable discrimination for characterising:

vegetated wetlands
salt flats
salt lakes
coastal land cover classes

The tasseled cap wetness transform translates the six spectral bands of Landsat into a single wetness index.  The wetness index can be used to identify areas in the landscape that are potentially wetlands or groundwater dependent ecosystems. The tasseled cap wetness percentiles captures how the wetness index behaves over time.  The percentiles are well suited to characterising wetlands, salt flats/salt lakes and coastal ecosystems. However, care should be applied when analysing the wetness index, as soil colour and fire scars can cause misleading results.

The 10th, 50th and 90th percentiles of the tasseled cap wetness index are intended to capture the extreme (10th and 90th percentile) values and long term average (50th percentile) values of the wetness index.  Percentiles are used in preference to minimum, maximum and mean, as the min/max/mean statistical measures are more sensitive to undetected cloud/cloud shadow, and can be misleading for non-normally distributed data.

The tasseled cap wetness percentiles are intended to complement the Water Observations from Space (WOfS) algorithm. WOfS is designed to discriminate open water, but the tasseled cap wetness identifies areas of water and areas where water and vegetation are mixed together; i.e. mangroves and palustrine wetlands.

If you are interested in terrestrial vegetation (where water in the pixel is not a factor), use the Fractional Cover product, which provides a better biophysical characterisation of green vegetation fraction, dry vegetation fraction and bare soil vegetation fraction.

We used the tasseled cap transforms described in Crist et al. (1985).

Crist, E. P. (1985). A TM Tasseled Cap equivalent transformation for reflectance factor data. Remote Sensing of Environment, 17(3), 301–306. https://doi.org/10.1016/0034-4257(85)90102-6

For service status information, see https://status.dea.ga.gov.au |

## OWS layer style*s* for the requested layer, duplicate if more than 1 or point a reusable existing style ##

| field | value |
|----- | ----|
| title  | Tasseled Cap Wetness 10th Percentile  |
| abstract |The 10th Percentile of Tasseled Cap Wetness Index (1986-2018) |  

### color ramp - provide values ###
| field | value |
| ----- | ----- |
| required band | TCW_PC_10 |

**color ramp**
```
    "range": [-1200.0, 0.0],
    "mpl_ramp": "gist_earth_r ",
    "legend": {
        "begin": -1200,
        "end": 0,
        "units": "Tasseled Cap Wetness Index",
        "decimal_places": 0,
        "ticks_every": 1000,
        },
```

| title  | Tasseled Cap Wetness 50th Percentile  |
| abstract |The 50th Percentile of Tasseled Cap Wetness Index (1986-2018) |  

### color ramp - provide values ###
| field | value |
| ----- | ----- |
| required band | TCW_PC_50 |

**color ramp**
```
    "range": [-1200.0, 0.0],
    "mpl_ramp": "gist_earth_r ",
    "legend": {
        "begin": -1200,
        "end": 0,
        "units": "Tasseled Cap Wetness Index",
        "decimal_places": 0,
        "ticks_every": 1000,
        },
```

| title  | Tasseled Cap Wetness 90th Percentile  |
| abstract |The 90th Percentile of Tasseled Cap Wetness Index (1986-2018) |  
### color ramp - provide values ###
| field | value |
| ----- | ----- |
| required band | TCW_PC_90 |
**color ramp**
```
    "range": [-1200.0, 0.0],
    "mpl_ramp": "gist_earth_r ",
    "legend": {
        "begin": -1200,
        "end": 0,
        "units": "Tasseled Cap Wetness Index",
        "decimal_places": 0,
        "ticks_every": 1000,
        },
```

## Input for terria catalog (this is for release, last step, easy task)## 

| field | value |
|----- | ----|
| Level 1	| DEA Wetness Percentiles |
| Level 2	| Tasseled Cap Wetness 10th Percentile |
| Level 2	| Tasseled Cap Wetness 50th Percentile |
| Level 2	| Tasseled Cap Wetness 90th Percentile |
| Layer name | Tasseled Cap Wetness 10th Percentile |
| Layer name | Tasseled Cap Wetness 50th Percentile |
| Layer name | Tasseled Cap Wetness 90th Percentile |

**Comment by vnewey** [comment]
Please let me know if you would like me to split this into 3 separate requests.
The description and symology is the same for the 3 layers. :)

**Comment by pindge** [comment]
@vnewey just confirming you actually want three layers? or one layer with 3 different styles, looking at some of the existing implementations, when the layer is different, the product is actually different. happy to go ur way, but wanted to clarify.

![image](https://user-images.githubusercontent.com/24644475/97662471-4f891800-1acb-11eb-9402-6477558701d9.png)

**Comment by vnewey** [comment]
Thanks for asking @pindge I will check with Leo.

**Comment by vnewey** [comment]
Hi @pindge, good spotting! 1 layer with 3 styles would be best.
Like the Fractional Cover Percentiles.
I am not sure how I define that in the OWS request.
the category would be **DEA Wetness Percentiles (Landsat)**
the layername would be **Tasseled Cap Wetness Percentiles**
styles would be: 10th Percentile, 50th Percentile and 90th Percentile
They use the bands: TCW_PC_10, TCW_PC_50, TCW_PC_90

Should I put in a new ows request?
Thanks!

**Comment by pindge** [comment]
thanks, its all clear now, this isnt about who can get the request right, its about to have enough information for **clarity** , like plan before execution.

**Comment by vnewey** [comment]
Thanks for your help! 
Have a great weekend!
