### ISSUE TITLE
Create PR Template

### ISSUE THREAD

**Issue by whatnick** [GeoscienceAustralia/dea-config#691]
This repository is a mono-repo and rapidly receiving lots of PR's create templates to break them up into various categories:
- Product / Metadata Definitions
- OWS Layer publications / styles
- Terria Catalog changes

Follow guidelines [here](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)

**Comment by pindge** [comment]
whats creating templates??? is it like automatic tagging/labelling or something?

**Comment by whatnick** [comment]
Updated issue, essentially attempting to get better PR's opened with a structured questionnaire, similar to what we have for issues.
