### ISSUE TITLE
terria catalogs and terria instance pairing 

### ISSUE THREAD

**Issue by pindge** [GeoscienceAustralia/dea-config#786]
This is to track all the terria-catalogs we manage or we dont manage, and all the terria instances that are related to us.

| Terrria instance       |  matching onload catalog         | terria instance description (who accesses it, its purpose, the process required for authorization before adding to it?? any insight?? |
| ------------- |:-------------:| :----------------|
| https://terria-cube.terria.io/       | https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/terria/dea.json | ????? |
| https://nationalmap.gov.au/       | ??? |  ???? |
| https://maps.dea.ga.gov.au/       |  https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/terria/dea-maps.json (soon to be replaced with https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/terria/dea-maps-v8.json) | ??? |

Could everyone contribute by raising awareness of any other terria catalogs that are related to us? and their corresponding terria-catalog?

at the end of this exercise, all the information collected will go to readme

**Comment by robbibt** [comment]
I've just clarified that the current DEA Maps catalogue is soon to be replaced with a new V8 equivalent

> (soon to be replaced with https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/terria/dea-maps-v8.json)

**Comment by pindge** [comment]
> I've just clarified that the current DEA Maps catalogue is soon to be replaced with a new V8 equivalent
> 
> > (soon to be replaced with https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/terria/dea-maps-v8.json)

Can you also confirm that the maps.dea.ga.gov.au actually maps to dea-maps.json? because i am not sure about maps.dea

**Comment by robbibt** [comment]
Correct: DEA Maps (maps.dea.ga.gov.au) is currently based on `dea-maps.json`. However, since DEA Maps was upgraded to version 8 of TerriaJS, changes to that config are no longer automatically updated on DEA Maps (so changes to that config currently do nothing). In the long run, we are revising `dea-maps-v8.json` to be the file that will map to DEA Maps.

**Comment by robbibt** [comment]
Yeah, all content in this issue is now out of data - should we close this @pindge? I'll add that info to the readme
