### ISSUE TITLE
terria catalog isn't applying dateformat correctly

### ISSUE THREAD

**Issue by pindge** [GeoscienceAustralia/dea-config#834]
![image](https://user-images.githubusercontent.com/24644475/132812398-a8c20827-e4a1-4358-aa6d-126646ba090c.png)

Land cover is an annual product when the catalog `dateformat` is configured correctly it only shows the `YEAR`, but right now its showing `dd/mm/yyyy time` 

```
"dateFormat": {
      "currentTime": "'Year: 'yyyy",
      "timelineTic": "yyyy"
}
```

**Comment by GypsyBojangles** [comment]
So that dateFormat syntax doesn't work in v8, we will need to get advice from TerriaJS team on what that should be,

**Comment by nf-s** [comment]
Hi @GypsyBojangles 

The `dateFormat` just a string property now, `timelineTic` isn't supported.

So the following should work:

```json
"dateFormat": "'Year: 'yyyy"
```

**Comment by GypsyBojangles** [comment]
Thankyou @nf-s !

**Comment by GypsyBojangles** [comment]
Added correct syntax to terria-cube catalog in PR #835
